### ISSUE TITLE
Is there a plan supporting resolve plugins ?

### ISSUE THREAD

**Issue by hikerpig** [web-infra-dev/rspack-resolver#16]
Our project in webpack relies on several enhanced-resolve plugin for dynamic path replacement or so.

So it would be nice if there is similar mechanism in rspack, otherwise we would need some extra efforts transforming the build process to rspack.

**Comment by chenjiahan** [comment]
Rspack has no plans to support "resolve.plugins" in the short term, as this configuration is deeply coupled with enhanced-resolve, which Rspack itself does not use. In addition, improper use of resolve plugins can likely result in slower build performance.

Currently, Rspack provides some resolve hooks through NormalModuleFactory, which can perform path replacement and other operations. See this document: https://rspack.dev/api/plugin-api/normal-module-factory-hooks
